### ISSUE TITLE
A record added in a Favorites list has its Record history GUID persist in the Favorite list after record is deleted

### ISSUE THREAD

**Issue by VEtique** [ansys/grantami-recordlists#165]
### 📝 Description of the feature

If a record is added to a published Favorites list and the record is then deleted, the original GUID of the original record still remains in the published Favorites list (fetched in PyGranta). 

The expected behavior would be that when a record is deleted from the database, the GUID is cleaned up from the Favorites lists as well, such that subsequent calls to grab a list of records from the Favorites List should not yield the GUID that was deleted. Or to have PyGranta not return (remove?) this GUID from all Favorites Lists.

This is observed in Granta MI 2023 R2.

### 🔗 Useful links and references

https://grantadesign.atlassian.net.mcas.ms/browse/MST-1519

**Comment by Andy-Grigg** [comment]
In the Favorites list architecture for UIs, it's the UI's responsibility to determine whether the list item should be shown to the user or not. This is pretty much just based on whether the user can resolve the record reference, taking into considering their role, access control permissions, version control permissions, etc. 

PyGranta essentially takes the place of a UI, it's just in code. As a result, I think this ultimately does fall on us to manage.

There is an endpoint we can use that was added in 2024 R1: https://github.com/ansys/grantami-serverapi-openapi/blob/4438fc13882108cbd70ea2ed0cfa2ecf51928568/ansys-grantami-serverapi-openapi/src/ansys/grantami/serverapi_openapi/api/records___record_histories_api.py#L27 However, it's a GET endpoint, so we'll need to iterate through each item separately to determine if it is resolvable, instead of just making a single batched request.

**Comment by Andy-Grigg** [comment]
It's worth clarifying that since the endpoint added above was added in 2024 R1, we can't cherry-pick this onto the v1.0 (2023 R2) release branch.

**Comment by Andy-Grigg** [comment]
There might be a multiple-histories version soon, but it's not available yet, and won't be in this release. We should look at parallelizing these requests.
