### ISSUE TITLE
`get_resolvable_list_items` returns empty list

### ISSUE THREAD

**Issue by ludovicsteinbach** [ansys/grantami-recordlists#218]
It's possible for multiple dbs to have the same GUID, in which case the existence of the record might be verified against the wrong db, making it always non resolvable.
We need to use another dict key

**Comment by Andy-Grigg** [comment]
Solution here is to probably have this map https://github.com/ansys/grantami-recordlists/blob/064ce1224a0ee496be661deb931d8f14da966744/src/ansys/grantami/recordlists/_connection.py#L611 as a map between guid and a list of keys, since multiple databases can have the same database guid.

We will then need to iterate through all keys for a guid, and return a positive result if at least one of them matches

**Comment by Andy-Grigg** [comment]
The associated PR has been merged, which includes test cases that validate that the bug has been fixed. There was a similar issue for database searches as well, which has also been resolved.

Note, this fix is only available in Granta MI 2024 R2.
