### ISSUE TITLE
Add compatibility information about supported Granta MI/package versions

### ISSUE THREAD

**Issue by NoahMDMi** [ansys/grantami-recordlists#283]
### Description of the modifications

While reading the [PyGranta Record Lists documentation](https://recordlists.grantami.docs.pyansys.com/version/stable/), I noticed the only information about Granta release version support is about the current version[^1]:
> To use this version of the `ansys.grantami.recordlists` package you must have access to a Granta MI 2024 R2 deployment. 

However, finding information about which versions of the package are compatible with other releases (i.e. 2023R2) is limited to[^2]:

> To install a release compatible with a specific version of Granta MI, use the [PyGranta](https://grantami.docs.pyansys.com/) meta-package with a requirement specifier:
> ```
> pip install pygranta==2023.2.0
> ```

Which is not a great solution if I am only looking to install the specific `ansys.grantami.recordlists` package. 

It would be nice to see a table in the documentation somewhere (perhaps on the PyGranta page) with information about what the latest supported package for each Granta MI version is, instead of relying on installing the entire PyGranta package. 

It is possible to manually search through every previous version of the package on PyPI to find this information, but extremely inconvenient. 

Thanks!

[^1]: https://recordlists.grantami.docs.pyansys.com/version/stable/#dependencies
[^2]: https://recordlists.grantami.docs.pyansys.com/version/stable/#installation

### Useful links and references

https://recordlists.grantami.docs.pyansys.com/version/stable/

**Comment by Andy-Grigg** [comment]
With the meta-package and calver-style versioning, we're ensuring compatibility with specific versions of MI, and that compatibility is self-documenting by use of the version number itself.

If we add this information somewhere else, it's something else to keep up to date, and there's the risk it's forgotten, and we end up with confusing documentation. We can't really document it either, because the release for this package (and other top-level PyGranta packages) has to happen _before_ the meta-package release.

Just so I understand a bit more, is the main issue with the meta-package approach that it installs additional packages?

We're moving towards a model where different parts of the Granta MI provided API will be wrapped by standalone packages, but that they will all be designed to work together as part of 'PyGranta'. As a result, we typically expect users to install the metapackage. There's relatively low overhead in doing this, since the majority of the size is in the reusable `ansys-openapi-common` and `ansys-grantami-serverapi-openapi` packages.

If you care about having an absolute-as-lean-as-possible environment, then it is possible to pin the package version manually, but in normal use I would recommend using the meta-package.

Do you have any other issues with using the meta-package?

**Comment by Andy-Grigg** [comment]
@NoahMDMi Please see https://grantami.docs.pyansys.com/version/dev/package_versions.html for a new page added to the PyGranta docs that lists the individual package versions for each version of MI. Does this address your issue?

**Comment by NoahMDMi** [comment]
This is exactly what I am looking for! Thank you 😄
